import type { ComponentType, SVGProps } from 'react'

export type LogoComponent = ComponentType<SVGProps<SVGSVGElement>>

// Catalog template id -> lazily loaded thesvg mark. One dynamic import per
// logo keeps them out of the initial bundle; templates with no entry fall
// back to their category icon.
export const TEMPLATE_LOGO_LOADERS: Record<
  string,
  () => Promise<{ default: LogoComponent }>
> = {
  'actual-budget': () => import('@thesvg/react/actual-budget'),
  adminer: () => import('@thesvg/react/adminer'),
  appsmith: () => import('@thesvg/react/appsmith'),
  audiobookshelf: () => import('@thesvg/react/audiobookshelf'),
  baserow: () => import('@thesvg/react/baserow'),
  bookstack: () => import('@thesvg/react/bookstack'),
  calcom: () => import('@thesvg/react/cal-com'),
  'calibre-web': () => import('@thesvg/react/calibre-web'),
  chatwoot: () => import('@thesvg/react/chatwoot'),
  clickhouse: () => import('@thesvg/react/clickhouse'),
  directus: () => import('@thesvg/react/directus'),
  duplicati: () => import('@thesvg/react/duplicati'),
  excalidraw: () => import('@thesvg/react/excalidraw'),
  'firefly-iii': () => import('@thesvg/react/firefly-iii'),
  formbricks: () => import('@thesvg/react/formbricks'),
  freshrss: () => import('@thesvg/react/freshrss'),
  ghost: () => import('@thesvg/react/ghost'),
  gitea: () => import('@thesvg/react/gitea'),
  'gitlab-ce': () => import('@thesvg/react/gitlab'),
  glance: () => import('@thesvg/react/glance'),
  grafana: () => import('@thesvg/react/grafana'),
  grocy: () => import('@thesvg/react/grocy'),
  healthchecks: () => import('@thesvg/react/healthchecks-badge'),
  hedgedoc: () => import('@thesvg/react/hedgedoc'),
  'home-assistant': () => import('@thesvg/react/home-assistant'),
  homebox: () => import('@thesvg/react/homebox'),
  homepage: () => import('@thesvg/react/homepage'),
  immich: () => import('@thesvg/react/immich'),
  influxdb: () => import('@thesvg/react/influxdb'),
  'invoice-ninja': () => import('@thesvg/react/invoice-ninja'),
  jellyfin: () => import('@thesvg/react/jellyfin'),
  'joplin-server': () => import('@thesvg/react/joplin'),
  kavita: () => import('@thesvg/react/kavita'),
  keycloak: () => import('@thesvg/react/keycloak'),
  leantime: () => import('@thesvg/react/leantime'),
  libretranslate: () => import('@thesvg/react/libretranslate'),
  linkwarden: () => import('@thesvg/react/linkwarden'),
  listmonk: () => import('@thesvg/react/listmonk'),
  matomo: () => import('@thesvg/react/matomo'),
  mattermost: () => import('@thesvg/react/mattermost'),
  mealie: () => import('@thesvg/react/mealie'),
  meilisearch: () => import('@thesvg/react/meilisearch'),
  metabase: () => import('@thesvg/react/metabase'),
  minio: () => import('@thesvg/react/minio'),
  n8n: () => import('@thesvg/react/n8n'),
  navidrome: () => import('@thesvg/react/navidrome'),
  nextcloud: () => import('@thesvg/react/nextcloud'),
  nocodb: () => import('@thesvg/react/nocodb'),
  'node-red': () => import('@thesvg/react/node-red'),
  ntfy: () => import('@thesvg/react/ntfy'),
  ollama: () => import('@thesvg/react/ollama'),
  'ollama-deepseek': () => import('@thesvg/react/ollama'),
  'ollama-llama3': () => import('@thesvg/react/ollama'),
  'ollama-mistral': () => import('@thesvg/react/ollama'),
  'ollama-phi': () => import('@thesvg/react/ollama'),
  'ollama-qwen': () => import('@thesvg/react/ollama'),
  'open-webui': () => import('@thesvg/react/open-webui'),
  outline: () => import('@thesvg/react/outline'),
  overseerr: () => import('@thesvg/react/overseerr'),
  'paperless-ngx': () => import('@thesvg/react/paperless-ngx'),
  passbolt: () => import('@thesvg/react/passbolt'),
  penpot: () => import('@thesvg/react/penpot'),
  'pi-hole': () => import('@thesvg/react/pi-hole'),
  plausible: () => import('@thesvg/react/plausible-analytics'),
  portainer: () => import('@thesvg/react/portainer'),
  prometheus: () => import('@thesvg/react/prometheus'),
  qbittorrent: () => import('@thesvg/react/qbittorrent'),
  qdrant: () => import('@thesvg/react/qdrant'),
  rabbitmq: () => import('@thesvg/react/rabbitmq'),
  radarr: () => import('@thesvg/react/radarr'),
  rocketchat: () => import('@thesvg/react/rocketdotchat'),
  searxng: () => import('@thesvg/react/searxng'),
  sonarr: () => import('@thesvg/react/sonarr'),
  'stirling-pdf': () => import('@thesvg/react/stirling-pdf'),
  syncthing: () => import('@thesvg/react/syncthing'),
  transmission: () => import('@thesvg/react/transmission'),
  trilium: () => import('@thesvg/react/trilium'),
  typesense: () => import('@thesvg/react/typesense'),
  umami: () => import('@thesvg/react/umami'),
  'uptime-kuma': () => import('@thesvg/react/uptime-kuma'),
  vaultwarden: () => import('@thesvg/react/vaultwarden'),
  vikunja: () => import('@thesvg/react/vikunja'),
  wallabag: () => import('@thesvg/react/wallabag'),
  weblate: () => import('@thesvg/react/weblate'),
  wikijs: () => import('@thesvg/react/wikidotjs'),
  wordpress: () => import('@thesvg/react/wordpress'),
}
