package api

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"sync"
	"time"

	"github.com/GLINCKER/levelrail/internal/githubapp"
	"github.com/GLINCKER/levelrail/internal/store"
)

// GitHubAppStore is the store surface the GitHub App connection
// handlers need. *store.DB satisfies this structurally, part of the
// core Store interface (github_app_connections always exists as a
// table even when empty, the same "core store, not an optional
// plug-in" shape ingressSettings/domains already establish).
type GitHubAppStore interface {
	GetGitHubAppConnection(ctx context.Context) (store.GitHubAppConnection, error)
	SaveGitHubAppConnection(ctx context.Context, c store.GitHubAppConnection) error
	UpdateGitHubAppInstallation(ctx context.Context, installationID int64, accountLogin string) error
	DeleteGitHubAppConnection(ctx context.Context) error
}

// GitHubAppSecrets is the surface the GitHub App handlers need from
// internal/secrets.Manager: both SetValue (storing client_secret/
// webhook_secret/private_key right after a successful code exchange)
// and Resolve (decrypting the private key back out, in memory only,
// immediately before signing a JWT). A different shape from
// BackupSecretsSetter (set-only) and internal/backup.SecretsResolver
// (resolve-only): this is the one credential-bearing feature in this
// codebase that both writes and reads back through internal/secrets
// from inside internal/api itself, because minting a fresh installation
// token on every repo/branch-listing call (see github_app_repos.go)
// needs the private key synchronously in the same request, not on a
// separate worker path the way internal/backup.Runner's own Resolve
// calls are. *secrets.Manager satisfies this structurally.
type GitHubAppSecrets interface {
	SetValue(ctx context.Context, serviceName, envKey, plaintext string) error
	Resolve(ctx context.Context, serviceName, envKey string) (string, error)
	DeleteAll(ctx context.Context, serviceName string) error
}

// GitHubAppClient is the surface internal/api needs from
// internal/githubapp.Client: manifest code exchange, installation
// lookup and token minting, and repo/branch listing. *githubapp.Client
// satisfies this structurally; tests substitute a hand-written fake
// (github_app_test.go), the same "narrow, consumer-defined interface"
// shape every other external-system boundary in this package uses
// (Builder, DockerPinger, BackupRunner).
type GitHubAppClient interface {
	ExchangeManifestCode(ctx context.Context, code string) (githubapp.Credentials, error)
	GetInstallation(ctx context.Context, appJWT string, installationID int64) (githubapp.InstallationInfo, error)
	MintInstallationToken(ctx context.Context, appJWT string, installationID int64) (githubapp.InstallationToken, error)
	ListInstallationRepos(ctx context.Context, token string) ([]githubapp.Repo, error)
	ListBranches(ctx context.Context, token, owner, repo string) ([]githubapp.Branch, error)
}

// registrationStateTTL bounds how long a manifest-flow "state" value
// (githubAppRegistrationState.begin) stays valid: generous enough to
// cover an operator's own confirmation click on GitHub's own manifest
// review page, short enough that an abandoned registration attempt
// doesn't leave a usable CSRF token lying around indefinitely.
const registrationStateTTL = 15 * time.Minute

// githubAppRegistrationState holds the single in-flight manifest-flow
// CSRF state value, generated by handleStartGitHubAppRegistration and
// checked (and consumed) by handleGitHubAppCallback. In-memory, not
// persisted: this control plane has exactly one operator and the
// manifest flow is a single, short-lived round trip through the
// browser, so surviving a process restart mid-flow isn't a real
// requirement, the same "in-memory is enough" reasoning
// internal/api's own sessionStore and loginLimiter already apply to
// comparable short-lived, single-admin state.
//
// Starting a new registration overwrites any still-pending one: only
// one registration can be in flight at a time, matching "one GitHub App
// connection per control plane" everywhere else in this feature.
type githubAppRegistrationState struct {
	mu        sync.Mutex
	state     string
	expiresAt time.Time
}

func newGitHubAppRegistrationState() *githubAppRegistrationState {
	return &githubAppRegistrationState{}
}

// begin generates a new random state value, stores it as the one
// pending registration, and returns it for the manifest form's
// ?state= query parameter.
func (s *githubAppRegistrationState) begin() (string, error) {
	// 32 random bytes (256 bits): well beyond "unguessable", GitHub's own
	// documented requirement for this parameter.
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("api: generate github app registration state: %w", err)
	}
	state := base64.RawURLEncoding.EncodeToString(buf)

	s.mu.Lock()
	s.state = state
	s.expiresAt = time.Now().Add(registrationStateTTL)
	s.mu.Unlock()

	return state, nil
}

// consume reports whether got matches the pending state and hasn't
// expired, clearing the pending state on a successful match so it can
// never be replayed. A mismatch does not clear the pending state, so a
// stray or malicious request carrying the wrong value can't cancel a
// legitimate registration that's still genuinely in flight.
func (s *githubAppRegistrationState) consume(got string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.state == "" || got == "" {
		return false
	}
	if time.Now().After(s.expiresAt) {
		s.state = ""
		return false
	}
	if got != s.state {
		return false
	}
	s.state = ""
	return true
}

// gitHubAppStatusResource is the wire shape for GET /api/v1/github-app.
// Deliberately no secret fields (client_secret/webhook_secret/
// private_key never leave internal/secrets through this or any other
// response body): AppID and ClientID are the only identity fields
// echoed back, both non-secret per this feature's own store design
// (migrations/0030_github_app_connection.sql's own comment).
type gitHubAppStatusResource struct {
	Connected    bool   `json:"connected"`
	AppID        int64  `json:"app_id,omitempty"`
	ClientID     string `json:"client_id,omitempty"`
	Installed    bool   `json:"installed"`
	AccountLogin string `json:"account_login,omitempty"`
	CreatedAt    string `json:"created_at,omitempty"`
}

// handleGetGitHubAppStatus handles GET /api/v1/github-app: the
// connection status the settings page renders (not connected /
// connected as <account> / connected but not yet installed).
// AbilityRoot: see router.go's own route registration comment for why
// every GitHub App connection route, including this read, shares the
// same tier as PUT /api/v1/settings/ingress rather than the plain
// AbilityRead visibility tier most other GET routes use.
func (rt *Router) handleGetGitHubAppStatus(w http.ResponseWriter, r *http.Request) {
	conn, err := rt.githubApp.GetGitHubAppConnection(r.Context())
	if errors.Is(err, store.ErrGitHubAppConnectionNotFound) {
		writeJSON(w, http.StatusOK, gitHubAppStatusResource{Connected: false})
		return
	}
	if err != nil {
		rt.logger.Error("api: get github app connection status failed", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}

	resource := gitHubAppStatusResource{
		Connected: true,
		AppID:     conn.AppID,
		ClientID:  conn.ClientID,
		CreatedAt: conn.CreatedAt,
	}
	if conn.InstallationID != nil {
		resource.Installed = true
	}
	if conn.AccountLogin != nil {
		resource.AccountLogin = *conn.AccountLogin
	}
	writeJSON(w, http.StatusOK, resource)
}

// handleDisconnectGitHubApp handles DELETE /api/v1/github-app. See
// store.DB.DeleteGitHubAppConnection's own doc comment for the known,
// accepted gap this shares with DeleteBackupTarget: the App's own
// secret values (client_secret/webhook_secret/private_key) are not
// erased from internal/secrets, only the store row that made them
// reachable through this feature. Does not call GitHub to uninstall or
// delete the App on GitHub's own side: this is a local
// "stop trusting this connection" action, not a remote teardown. An
// operator who wants the App itself gone from GitHub must delete it
// from github.com/settings/apps themselves.
func (rt *Router) handleDisconnectGitHubApp(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	err := rt.githubApp.DeleteGitHubAppConnection(ctx)
	if errors.Is(err, store.ErrGitHubAppConnectionNotFound) {
		writeError(w, http.StatusNotFound, "no github app is connected")
		return
	}
	if err != nil {
		rt.logger.Error("api: disconnect github app failed", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}

	// The connection row is gone; the App's client_secret/webhook_secret/
	// private_key must go with it, not linger decryptable under the same
	// sentinel key indefinitely (see DeleteAll's own doc comment). A real
	// connection row is only ever created by handleGitHubAppCallback,
	// itself gated on rt.githubAppSecrets != nil, but this checks again
	// rather than assuming: a row can also reach the store directly
	// (tests, a future migration/import path) without that invariant
	// holding.
	if rt.githubAppSecrets != nil {
		if err := rt.githubAppSecrets.DeleteAll(ctx, store.GitHubAppSecretsKey()); err != nil {
			rt.logger.Error("api: delete github app secrets failed", slog.String("error", err.Error()))
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
	}

	w.WriteHeader(http.StatusNoContent)
}

// errGitHubAppNoPrimaryDomain is githubAppBaseURL's own sentinel for
// "ingress_settings.primary_domain is unset", so callers can distinguish
// that specific, actionable case from a genuine store error.
var errGitHubAppNoPrimaryDomain = errors.New("api: primary domain is not configured")

// githubAppBaseURL derives this control plane's own public, reachable
// origin from store.IngressSettings.PrimaryDomain (PUT
// /api/v1/settings/ingress), the same field
// internal/reconcile/ingress's WithDashboardDial route already treats
// as "the control plane's own hostname" when one is configured. Always
// https: PrimaryDomain is meant to be served by embedded Caddy with a
// real certificate (ACME or Caddy's own internal issuer), matching this
// project's own architecture (section 4.5), so there is no legitimate
// plain-http case here to support.
//
// Returns errGitHubAppNoPrimaryDomain if PrimaryDomain is empty: GitHub
// App registration needs a real, working callback URL, and there is no
// meaningful fallback (not "localhost", which GitHub cannot reach in a
// real deployment either) to substitute for an operator explicitly
// configuring one first.
func (rt *Router) githubAppBaseURL(ctx context.Context) (string, error) {
	settings, err := rt.ingressSettings.GetIngressSettings(ctx)
	if err != nil {
		return "", fmt.Errorf("api: get ingress settings: %w", err)
	}
	if settings.PrimaryDomain == "" {
		return "", errGitHubAppNoPrimaryDomain
	}
	return "https://" + settings.PrimaryDomain, nil
}
