package api

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"sync"
	"time"
)

// pendingStateTTL bounds how long a single-use CSRF state value stays
// valid: generous enough to cover an operator's own confirmation click
// on the provider's authorization page, short enough that an abandoned
// connect attempt doesn't leave a usable CSRF token lying around
// indefinitely.
const pendingStateTTL = 15 * time.Minute

// pendingState holds one in-flight browser-redirect connect attempt's
// CSRF state value, plus an arbitrary caller-supplied value carried
// alongside it from begin through to consume: generated by a
// register/authorize handler and consumed by the matching callback.
// In-memory, not persisted, since this control plane has exactly one
// operator and every connect flow is a single, short-lived round trip
// through the browser. Shared across every git provider's own state
// field (githubAppState, gitlabAppState, ...) rather than one type per
// provider.
//
// The carried value exists for GitHub Enterprise Server support
// (docs/design/git-provider-integrations.md): a GitHub App registration
// targets a specific instance chosen before the redirect, but nothing
// about the App exists yet for that instance to be persisted against
// until the callback actually runs (unlike GitLab, whose instance_url
// is already saved in gitlab_app_connections before its OAuth redirect
// begins). Most callers that have nothing to carry pass an empty value.
type pendingState struct {
	mu        sync.Mutex
	state     string
	value     string
	expiresAt time.Time
}

func newPendingState() *pendingState {
	return &pendingState{}
}

func (s *pendingState) begin(value string) (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("api: generate oauth state: %w", err)
	}
	state := base64.RawURLEncoding.EncodeToString(buf)

	s.mu.Lock()
	s.state = state
	s.value = value
	s.expiresAt = time.Now().Add(pendingStateTTL)
	s.mu.Unlock()

	return state, nil
}

// consume reports whether got matches the pending state and hasn't
// expired, returning the value passed to begin alongside it. A mismatch
// (or an already-consumed/expired state) returns ("", false) without
// clearing a still-genuinely-pending state, so a stray or malicious
// request carrying the wrong value can't cancel a legitimate attempt
// still in flight.
func (s *pendingState) consume(got string) (string, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.state == "" || got == "" {
		return "", false
	}
	if time.Now().After(s.expiresAt) {
		s.state = ""
		s.value = ""
		return "", false
	}
	if got != s.state {
		return "", false
	}
	value := s.value
	s.state = ""
	s.value = ""
	return value, true
}
