package api

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"sync"
	"time"
)

// pendingStateTTL bounds how long a single-use CSRF state value stays
// valid: generous enough to cover an operator's own confirmation click
// on the provider's authorization page, short enough that an abandoned
// connect attempt doesn't leave a usable CSRF token lying around
// indefinitely.
const pendingStateTTL = 15 * time.Minute

// pendingState holds one in-flight browser-redirect connect attempt's
// CSRF state value: generated by a register/authorize handler and
// consumed by the matching callback. In-memory, not persisted, since
// this control plane has exactly one operator and every connect flow
// is a single, short-lived round trip through the browser. Shared
// across every git provider's own state field (githubAppState,
// gitlabAppState, ...) rather than one type per provider.
type pendingState struct {
	mu        sync.Mutex
	state     string
	expiresAt time.Time
}

func newPendingState() *pendingState {
	return &pendingState{}
}

func (s *pendingState) begin() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("api: generate oauth state: %w", err)
	}
	state := base64.RawURLEncoding.EncodeToString(buf)

	s.mu.Lock()
	s.state = state
	s.expiresAt = time.Now().Add(pendingStateTTL)
	s.mu.Unlock()

	return state, nil
}

func (s *pendingState) consume(got string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.state == "" || got == "" {
		return false
	}
	if time.Now().After(s.expiresAt) {
		s.state = ""
		return false
	}
	if got != s.state {
		return false
	}
	s.state = ""
	return true
}
