// TASKS.md 3.2: the wire contract for ADR 003's reverse-dialed gRPC
// agent. Message shapes mirror internal/docker's Go types (ContainerSpec,
// ContainerState, Event, ImageInfo, VolumeMount, PortBinding, Resources)
// field for field, deliberately: this is the exact narrow surface
// internal/agent.Transport already committed to in TASKS.md 3.1
// (docker.Runtime's own 9 methods, no more), not a redesign.
//
// AgentService is defined from the control plane's perspective (it is
// the gRPC *server*, since it has the one stable, well-known address
// every agent dials into) even though the agent is always the one who
// physically opens the connection (ADR 003: "the agent runs on every
// managed node and dials out"). Session is the one call an agent makes:
// a single long-lived bidirectional stream, kept open for the agent
// process's lifetime. The control plane sends AgentRequest messages down
// that stream (each carrying a request_id); the agent replies with
// AgentResponse messages carrying the same request_id, allowing many
// logical request/response pairs, including one persistently-streaming
// one (WatchEvents), to share the single physical connection. This is
// what "reverse-dialed" looks like at the RPC layer: TCP/TLS connection
// direction and logical request direction are independent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JoinToken string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// NodeName is what the enrolling node wants to be called
	// (store.Node.Name); the control plane still enforces uniqueness
	// (store.ErrNodeNameTaken) the same way it would for any other
	// SaveNode caller.
	NodeName      string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *EnrollRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeID is the store.Node.ID the control plane assigned; the agent
	// persists this alongside its certificate so subsequent Session
	// reconnects can identify themselves before the mTLS handshake even
	// completes (the cert's own CommonName already encodes it too, this
	// is the same value spelled out for the agent's own local bookkeeping).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ClientCertPEM/ClientKeyPEM are this node's new mTLS identity.
	// ClientKeyPEM never leaves this one response: it isn't persisted by
	// the control plane, isn't logged, and isn't retrievable again,
	// matching every other "shown once" credential in this codebase
	// (API tokens, node join tokens themselves).
	ClientCertPem []byte `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem  []byte `protobuf:"bytes,3,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	// CACertPEM is the control plane's own CA certificate, so the agent
	// can verify the control plane's TLS server certificate on every
	// future connection without trusting the system root store (this is
	// a private, self-issued PKI for exactly this one relationship, not a
	// publicly-trusted certificate).
	CaCertPem     []byte `protobuf:"bytes,4,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetClientKeyPem() []byte {
	if x != nil {
		return x.ClientKeyPem
	}
	return nil
}

func (x *EnrollResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

// AgentMessage is one frame the agent sends up the Session stream:
// either a reply to an outstanding AgentRequest, or an unprompted
// streamed Docker event.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Response
	//	*AgentMessage_Event
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetResponse() *AgentResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *ProxiedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Response struct {
	Response *AgentResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type AgentMessage_Event struct {
	Event *ProxiedEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*AgentMessage_Response) isAgentMessage_Payload() {}

func (*AgentMessage_Event) isAgentMessage_Payload() {}

// ControlMessage is one frame the control plane sends down the Session
// stream: always a request. (A dedicated envelope message, not just
// AgentRequest directly, so this type can grow a second oneof arm later
// without an incompatible wire change, the same reasoning AgentMessage
// already needs one today for its two arms.)
type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *AgentRequest          `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetRequest() *AgentRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// AgentRequest is one control-plane-issued operation, tagged with
// request_id so out-of-order AgentResponse frames on the same stream
// still resolve to the right caller (internal/agent's multiplexer,
// TASKS.md 3.2, owns matching these).
type AgentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*AgentRequest_InspectByName
	//	*AgentRequest_Create
	//	*AgentRequest_Start
	//	*AgentRequest_Stop
	//	*AgentRequest_Remove
	//	*AgentRequest_ListImages
	//	*AgentRequest_ListByPrefix
	//	*AgentRequest_EnsureVolume
	//	*AgentRequest_WatchEvents
	Op            isAgentRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRequest) GetOp() isAgentRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *AgentRequest) GetInspectByName() *InspectByNameRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_InspectByName); ok {
			return x.InspectByName
		}
	}
	return nil
}

func (x *AgentRequest) GetCreate() *CreateRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *AgentRequest) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AgentRequest) GetStop() *StopRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *AgentRequest) GetRemove() *RemoveRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *AgentRequest) GetListImages() *ListImagesRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_ListImages); ok {
			return x.ListImages
		}
	}
	return nil
}

func (x *AgentRequest) GetListByPrefix() *ListByPrefixRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_ListByPrefix); ok {
			return x.ListByPrefix
		}
	}
	return nil
}

func (x *AgentRequest) GetEnsureVolume() *EnsureVolumeRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_EnsureVolume); ok {
			return x.EnsureVolume
		}
	}
	return nil
}

func (x *AgentRequest) GetWatchEvents() *WatchEventsRequest {
	if x != nil {
		if x, ok := x.Op.(*AgentRequest_WatchEvents); ok {
			return x.WatchEvents
		}
	}
	return nil
}

type isAgentRequest_Op interface {
	isAgentRequest_Op()
}

type AgentRequest_InspectByName struct {
	InspectByName *InspectByNameRequest `protobuf:"bytes,2,opt,name=inspect_by_name,json=inspectByName,proto3,oneof"`
}

type AgentRequest_Create struct {
	Create *CreateRequest `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type AgentRequest_Start struct {
	Start *StartRequest `protobuf:"bytes,4,opt,name=start,proto3,oneof"`
}

type AgentRequest_Stop struct {
	Stop *StopRequest `protobuf:"bytes,5,opt,name=stop,proto3,oneof"`
}

type AgentRequest_Remove struct {
	Remove *RemoveRequest `protobuf:"bytes,6,opt,name=remove,proto3,oneof"`
}

type AgentRequest_ListImages struct {
	ListImages *ListImagesRequest `protobuf:"bytes,7,opt,name=list_images,json=listImages,proto3,oneof"`
}

type AgentRequest_ListByPrefix struct {
	ListByPrefix *ListByPrefixRequest `protobuf:"bytes,8,opt,name=list_by_prefix,json=listByPrefix,proto3,oneof"`
}

type AgentRequest_EnsureVolume struct {
	EnsureVolume *EnsureVolumeRequest `protobuf:"bytes,9,opt,name=ensure_volume,json=ensureVolume,proto3,oneof"`
}

type AgentRequest_WatchEvents struct {
	WatchEvents *WatchEventsRequest `protobuf:"bytes,10,opt,name=watch_events,json=watchEvents,proto3,oneof"`
}

func (*AgentRequest_InspectByName) isAgentRequest_Op() {}

func (*AgentRequest_Create) isAgentRequest_Op() {}

func (*AgentRequest_Start) isAgentRequest_Op() {}

func (*AgentRequest_Stop) isAgentRequest_Op() {}

func (*AgentRequest_Remove) isAgentRequest_Op() {}

func (*AgentRequest_ListImages) isAgentRequest_Op() {}

func (*AgentRequest_ListByPrefix) isAgentRequest_Op() {}

func (*AgentRequest_EnsureVolume) isAgentRequest_Op() {}

func (*AgentRequest_WatchEvents) isAgentRequest_Op() {}

// AgentResponse is the agent's answer to exactly one AgentRequest,
// carrying the same request_id.
type AgentResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Error is set (and every field below unset) when the underlying
	// internal/docker.Runtime call itself returned an error: the
	// multiplexer surfaces this as a real Go error to the caller, never
	// silently treated as a zero-value success.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*AgentResponse_InspectByName
	//	*AgentResponse_Create
	//	*AgentResponse_ListImages
	//	*AgentResponse_ListByPrefix
	//	*AgentResponse_Empty
	Result        isAgentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentResponse) GetResult() isAgentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentResponse) GetInspectByName() *InspectByNameResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_InspectByName); ok {
			return x.InspectByName
		}
	}
	return nil
}

func (x *AgentResponse) GetCreate() *CreateResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *AgentResponse) GetListImages() *ListImagesResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_ListImages); ok {
			return x.ListImages
		}
	}
	return nil
}

func (x *AgentResponse) GetListByPrefix() *ListByPrefixResponse {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_ListByPrefix); ok {
			return x.ListByPrefix
		}
	}
	return nil
}

func (x *AgentResponse) GetEmpty() *Empty {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

type isAgentResponse_Result interface {
	isAgentResponse_Result()
}

type AgentResponse_InspectByName struct {
	InspectByName *InspectByNameResponse `protobuf:"bytes,3,opt,name=inspect_by_name,json=inspectByName,proto3,oneof"`
}

type AgentResponse_Create struct {
	Create *CreateResponse `protobuf:"bytes,4,opt,name=create,proto3,oneof"`
}

type AgentResponse_ListImages struct {
	ListImages *ListImagesResponse `protobuf:"bytes,5,opt,name=list_images,json=listImages,proto3,oneof"`
}

type AgentResponse_ListByPrefix struct {
	ListByPrefix *ListByPrefixResponse `protobuf:"bytes,6,opt,name=list_by_prefix,json=listByPrefix,proto3,oneof"`
}

type AgentResponse_Empty struct {
	// Start, Stop, Remove, EnsureVolume, and the WatchEvents
	// acknowledgment all return nothing but success/Error above, so
	// none of them needs its own response message.
	Empty *Empty `protobuf:"bytes,7,opt,name=empty,proto3,oneof"`
}

func (*AgentResponse_InspectByName) isAgentResponse_Result() {}

func (*AgentResponse_Create) isAgentResponse_Result() {}

func (*AgentResponse_ListImages) isAgentResponse_Result() {}

func (*AgentResponse_ListByPrefix) isAgentResponse_Result() {}

func (*AgentResponse_Empty) isAgentResponse_Result() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HostPort      int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PortBinding) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortBinding) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortBinding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes   int64                  `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NanoCpus      int64                  `protobuf:"varint,2,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Resources) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Resources) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerPath string                 `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *VolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

type ContainerSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image     string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Ports     []*PortBinding         `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Env       map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources *Resources             `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"` // unset means internal/docker.ContainerSpec.Resources == nil
	Volumes   []*VolumeMount         `protobuf:"bytes,6,rep,name=volumes,proto3" json:"volumes,omitempty"`
	// DNS mirrors internal/docker.ContainerSpec.DNS. Empty means Docker's
	// own embedded resolver, unchanged from before this field existed.
	Dns           []string `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ContainerSpec) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ContainerSpec) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Running       bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	Ports         []*PortBinding         `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerState) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerState) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ContainerState) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ImageInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ProxiedEvent mirrors internal/docker.Event, relayed unprompted as it
// happens on the agent's own local WatchEvents stream (ADR 003's
// event-push design), scoped to the one watch_events call currently
// active (a fresh watch_id per WatchEventsRequest, so a control plane
// that starts and stops watching doesn't get events crossed between
// watches).
type ProxiedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // internal/docker.EventAction: "start" | "die" | "stop"
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxiedEvent) Reset() {
	*x = ProxiedEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxiedEvent) ProtoMessage() {}

func (x *ProxiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxiedEvent.ProtoReflect.Descriptor instead.
func (*ProxiedEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ProxiedEvent) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

func (x *ProxiedEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ProxiedEvent) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ProxiedEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type InspectByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectByNameRequest) Reset() {
	*x = InspectByNameRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectByNameRequest) ProtoMessage() {}

func (x *InspectByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectByNameRequest.ProtoReflect.Descriptor instead.
func (*InspectByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *InspectByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InspectByNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found is false when internal/docker.Runtime.InspectByName's own
	// (nil, nil) "not found, not an error" contract applies: state below
	// is then unset, not a zero-valued ContainerState pretending to be a
	// real one.
	Found         bool            `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	State         *ContainerState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectByNameResponse) Reset() {
	*x = InspectByNameResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectByNameResponse) ProtoMessage() {}

func (x *InspectByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectByNameResponse.ProtoReflect.Descriptor instead.
func (*InspectByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InspectByNameResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *InspectByNameResponse) GetState() *ContainerState {
	if x != nil {
		return x.State
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ContainerSpec         `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CreateRequest) GetSpec() *ContainerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *StartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // internal/docker.Runtime.Stop's time.Duration, in milliseconds; negative means wait indefinitely
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *StopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ListImagesRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageInfo           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ListImagesResponse) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

type ListByPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPrefixRequest) Reset() {
	*x = ListByPrefixRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPrefixRequest) ProtoMessage() {}

func (x *ListByPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPrefixRequest.ProtoReflect.Descriptor instead.
func (*ListByPrefixRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ListByPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListByPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerState      `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPrefixResponse) Reset() {
	*x = ListByPrefixResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPrefixResponse) ProtoMessage() {}

func (x *ListByPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPrefixResponse.ProtoReflect.Descriptor instead.
func (*ListByPrefixResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ListByPrefixResponse) GetContainers() []*ContainerState {
	if x != nil {
		return x.Containers
	}
	return nil
}

type EnsureVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureVolumeRequest) Reset() {
	*x = EnsureVolumeRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVolumeRequest) ProtoMessage() {}

func (x *EnsureVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVolumeRequest.ProtoReflect.Descriptor instead.
func (*EnsureVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *EnsureVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// WatchEventsRequest starts (or, sent a second time with the same
// watch_id, is meaningless and rejected: one watch per Session,
// matching internal/docker.Runtime.Events' own "until ctx is cancelled"
// single-stream contract) the agent's relay of its local Docker event
// stream as ProxiedEvent frames on the same physical Session stream.
// There is no corresponding "stop watching" request: the watch runs for
// the Session's own lifetime, ending only when the stream itself closes,
// the same lifetime Events(ctx) already ties to ctx cancellation.
type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       string                 `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *WatchEventsRequest) GetWatchId() string {
	if x != nil {
		return x.WatchId
	}
	return ""
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x12levelrail.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"\x97\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\fR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x03 \x01(\fR\fclientKeyPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x04 \x01(\fR\tcaCertPem\"\x94\x01\n" +
	"\fAgentMessage\x12?\n" +
	"\bresponse\x18\x01 \x01(\v2!.levelrail.agent.v1.AgentResponseH\x00R\bresponse\x128\n" +
	"\x05event\x18\x02 \x01(\v2 .levelrail.agent.v1.ProxiedEventH\x00R\x05eventB\t\n" +
	"\apayload\"L\n" +
	"\x0eControlMessage\x12:\n" +
	"\arequest\x18\x01 \x01(\v2 .levelrail.agent.v1.AgentRequestR\arequest\"\xaa\x05\n" +
	"\fAgentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12R\n" +
	"\x0finspect_by_name\x18\x02 \x01(\v2(.levelrail.agent.v1.InspectByNameRequestH\x00R\rinspectByName\x12;\n" +
	"\x06create\x18\x03 \x01(\v2!.levelrail.agent.v1.CreateRequestH\x00R\x06create\x128\n" +
	"\x05start\x18\x04 \x01(\v2 .levelrail.agent.v1.StartRequestH\x00R\x05start\x125\n" +
	"\x04stop\x18\x05 \x01(\v2\x1f.levelrail.agent.v1.StopRequestH\x00R\x04stop\x12;\n" +
	"\x06remove\x18\x06 \x01(\v2!.levelrail.agent.v1.RemoveRequestH\x00R\x06remove\x12H\n" +
	"\vlist_images\x18\a \x01(\v2%.levelrail.agent.v1.ListImagesRequestH\x00R\n" +
	"listImages\x12O\n" +
	"\x0elist_by_prefix\x18\b \x01(\v2'.levelrail.agent.v1.ListByPrefixRequestH\x00R\flistByPrefix\x12N\n" +
	"\rensure_volume\x18\t \x01(\v2'.levelrail.agent.v1.EnsureVolumeRequestH\x00R\fensureVolume\x12K\n" +
	"\fwatch_events\x18\n" +
	" \x01(\v2&.levelrail.agent.v1.WatchEventsRequestH\x00R\vwatchEventsB\x04\n" +
	"\x02op\"\xb1\x03\n" +
	"\rAgentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12S\n" +
	"\x0finspect_by_name\x18\x03 \x01(\v2).levelrail.agent.v1.InspectByNameResponseH\x00R\rinspectByName\x12<\n" +
	"\x06create\x18\x04 \x01(\v2\".levelrail.agent.v1.CreateResponseH\x00R\x06create\x12I\n" +
	"\vlist_images\x18\x05 \x01(\v2&.levelrail.agent.v1.ListImagesResponseH\x00R\n" +
	"listImages\x12P\n" +
	"\x0elist_by_prefix\x18\x06 \x01(\v2(.levelrail.agent.v1.ListByPrefixResponseH\x00R\flistByPrefix\x121\n" +
	"\x05empty\x18\a \x01(\v2\x19.levelrail.agent.v1.EmptyH\x00R\x05emptyB\b\n" +
	"\x06result\"\a\n" +
	"\x05Empty\"m\n" +
	"\vPortBinding\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"K\n" +
	"\tResources\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x03R\vmemoryBytes\x12\x1b\n" +
	"\tnano_cpus\x18\x02 \x01(\x03R\bnanoCpus\"H\n" +
	"\vVolumeMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\"\xf0\x02\n" +
	"\rContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x125\n" +
	"\x05ports\x18\x03 \x03(\v2\x1f.levelrail.agent.v1.PortBindingR\x05ports\x12<\n" +
	"\x03env\x18\x04 \x03(\v2*.levelrail.agent.v1.ContainerSpec.EnvEntryR\x03env\x12;\n" +
	"\tresources\x18\x05 \x01(\v2\x1d.levelrail.agent.v1.ResourcesR\tresources\x129\n" +
	"\avolumes\x18\x06 \x03(\v2\x1f.levelrail.agent.v1.VolumeMountR\avolumes\x12\x10\n" +
	"\x03dns\x18\a \x03(\tR\x03dns\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x0eContainerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x125\n" +
	"\x05ports\x18\x05 \x03(\v2\x1f.levelrail.agent.v1.PortBindingR\x05ports\"X\n" +
	"\tImageInfo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x98\x01\n" +
	"\fProxiedEvent\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"*\n" +
	"\x14InspectByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\x15InspectByNameResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x128\n" +
	"\x05state\x18\x02 \x01(\v2\".levelrail.agent.v1.ContainerStateR\x05state\"F\n" +
	"\rCreateRequest\x125\n" +
	"\x04spec\x18\x01 \x01(\v2!.levelrail.agent.v1.ContainerSpecR\x04spec\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fStartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\vStopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"5\n" +
	"\rRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"'\n" +
	"\x11ListImagesRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"K\n" +
	"\x12ListImagesResponse\x125\n" +
	"\x06images\x18\x01 \x03(\v2\x1d.levelrail.agent.v1.ImageInfoR\x06images\"-\n" +
	"\x13ListByPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"Z\n" +
	"\x14ListByPrefixResponse\x12B\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\".levelrail.agent.v1.ContainerStateR\n" +
	"containers\")\n" +
	"\x13EnsureVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x12WatchEventsRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\tR\awatchId2\xb4\x01\n" +
	"\fAgentService\x12O\n" +
	"\x06Enroll\x12!.levelrail.agent.v1.EnrollRequest\x1a\".levelrail.agent.v1.EnrollResponse\x12S\n" +
	"\aSession\x12 .levelrail.agent.v1.AgentMessage\x1a\".levelrail.agent.v1.ControlMessage(\x010\x01B>Z<github.com/GLINCKER/levelrail/internal/agent/agentpb;agentpbb\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: levelrail.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: levelrail.agent.v1.EnrollResponse
	(*AgentMessage)(nil),          // 2: levelrail.agent.v1.AgentMessage
	(*ControlMessage)(nil),        // 3: levelrail.agent.v1.ControlMessage
	(*AgentRequest)(nil),          // 4: levelrail.agent.v1.AgentRequest
	(*AgentResponse)(nil),         // 5: levelrail.agent.v1.AgentResponse
	(*Empty)(nil),                 // 6: levelrail.agent.v1.Empty
	(*PortBinding)(nil),           // 7: levelrail.agent.v1.PortBinding
	(*Resources)(nil),             // 8: levelrail.agent.v1.Resources
	(*VolumeMount)(nil),           // 9: levelrail.agent.v1.VolumeMount
	(*ContainerSpec)(nil),         // 10: levelrail.agent.v1.ContainerSpec
	(*ContainerState)(nil),        // 11: levelrail.agent.v1.ContainerState
	(*ImageInfo)(nil),             // 12: levelrail.agent.v1.ImageInfo
	(*ProxiedEvent)(nil),          // 13: levelrail.agent.v1.ProxiedEvent
	(*InspectByNameRequest)(nil),  // 14: levelrail.agent.v1.InspectByNameRequest
	(*InspectByNameResponse)(nil), // 15: levelrail.agent.v1.InspectByNameResponse
	(*CreateRequest)(nil),         // 16: levelrail.agent.v1.CreateRequest
	(*CreateResponse)(nil),        // 17: levelrail.agent.v1.CreateResponse
	(*StartRequest)(nil),          // 18: levelrail.agent.v1.StartRequest
	(*StopRequest)(nil),           // 19: levelrail.agent.v1.StopRequest
	(*RemoveRequest)(nil),         // 20: levelrail.agent.v1.RemoveRequest
	(*ListImagesRequest)(nil),     // 21: levelrail.agent.v1.ListImagesRequest
	(*ListImagesResponse)(nil),    // 22: levelrail.agent.v1.ListImagesResponse
	(*ListByPrefixRequest)(nil),   // 23: levelrail.agent.v1.ListByPrefixRequest
	(*ListByPrefixResponse)(nil),  // 24: levelrail.agent.v1.ListByPrefixResponse
	(*EnsureVolumeRequest)(nil),   // 25: levelrail.agent.v1.EnsureVolumeRequest
	(*WatchEventsRequest)(nil),    // 26: levelrail.agent.v1.WatchEventsRequest
	nil,                           // 27: levelrail.agent.v1.ContainerSpec.EnvEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: levelrail.agent.v1.AgentMessage.response:type_name -> levelrail.agent.v1.AgentResponse
	13, // 1: levelrail.agent.v1.AgentMessage.event:type_name -> levelrail.agent.v1.ProxiedEvent
	4,  // 2: levelrail.agent.v1.ControlMessage.request:type_name -> levelrail.agent.v1.AgentRequest
	14, // 3: levelrail.agent.v1.AgentRequest.inspect_by_name:type_name -> levelrail.agent.v1.InspectByNameRequest
	16, // 4: levelrail.agent.v1.AgentRequest.create:type_name -> levelrail.agent.v1.CreateRequest
	18, // 5: levelrail.agent.v1.AgentRequest.start:type_name -> levelrail.agent.v1.StartRequest
	19, // 6: levelrail.agent.v1.AgentRequest.stop:type_name -> levelrail.agent.v1.StopRequest
	20, // 7: levelrail.agent.v1.AgentRequest.remove:type_name -> levelrail.agent.v1.RemoveRequest
	21, // 8: levelrail.agent.v1.AgentRequest.list_images:type_name -> levelrail.agent.v1.ListImagesRequest
	23, // 9: levelrail.agent.v1.AgentRequest.list_by_prefix:type_name -> levelrail.agent.v1.ListByPrefixRequest
	25, // 10: levelrail.agent.v1.AgentRequest.ensure_volume:type_name -> levelrail.agent.v1.EnsureVolumeRequest
	26, // 11: levelrail.agent.v1.AgentRequest.watch_events:type_name -> levelrail.agent.v1.WatchEventsRequest
	15, // 12: levelrail.agent.v1.AgentResponse.inspect_by_name:type_name -> levelrail.agent.v1.InspectByNameResponse
	17, // 13: levelrail.agent.v1.AgentResponse.create:type_name -> levelrail.agent.v1.CreateResponse
	22, // 14: levelrail.agent.v1.AgentResponse.list_images:type_name -> levelrail.agent.v1.ListImagesResponse
	24, // 15: levelrail.agent.v1.AgentResponse.list_by_prefix:type_name -> levelrail.agent.v1.ListByPrefixResponse
	6,  // 16: levelrail.agent.v1.AgentResponse.empty:type_name -> levelrail.agent.v1.Empty
	7,  // 17: levelrail.agent.v1.ContainerSpec.ports:type_name -> levelrail.agent.v1.PortBinding
	27, // 18: levelrail.agent.v1.ContainerSpec.env:type_name -> levelrail.agent.v1.ContainerSpec.EnvEntry
	8,  // 19: levelrail.agent.v1.ContainerSpec.resources:type_name -> levelrail.agent.v1.Resources
	9,  // 20: levelrail.agent.v1.ContainerSpec.volumes:type_name -> levelrail.agent.v1.VolumeMount
	7,  // 21: levelrail.agent.v1.ContainerState.ports:type_name -> levelrail.agent.v1.PortBinding
	28, // 22: levelrail.agent.v1.ImageInfo.created_at:type_name -> google.protobuf.Timestamp
	28, // 23: levelrail.agent.v1.ProxiedEvent.time:type_name -> google.protobuf.Timestamp
	11, // 24: levelrail.agent.v1.InspectByNameResponse.state:type_name -> levelrail.agent.v1.ContainerState
	10, // 25: levelrail.agent.v1.CreateRequest.spec:type_name -> levelrail.agent.v1.ContainerSpec
	12, // 26: levelrail.agent.v1.ListImagesResponse.images:type_name -> levelrail.agent.v1.ImageInfo
	11, // 27: levelrail.agent.v1.ListByPrefixResponse.containers:type_name -> levelrail.agent.v1.ContainerState
	0,  // 28: levelrail.agent.v1.AgentService.Enroll:input_type -> levelrail.agent.v1.EnrollRequest
	2,  // 29: levelrail.agent.v1.AgentService.Session:input_type -> levelrail.agent.v1.AgentMessage
	1,  // 30: levelrail.agent.v1.AgentService.Enroll:output_type -> levelrail.agent.v1.EnrollResponse
	3,  // 31: levelrail.agent.v1.AgentService.Session:output_type -> levelrail.agent.v1.ControlMessage
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Response)(nil),
		(*AgentMessage_Event)(nil),
	}
	file_proto_agent_v1_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentRequest_InspectByName)(nil),
		(*AgentRequest_Create)(nil),
		(*AgentRequest_Start)(nil),
		(*AgentRequest_Stop)(nil),
		(*AgentRequest_Remove)(nil),
		(*AgentRequest_ListImages)(nil),
		(*AgentRequest_ListByPrefix)(nil),
		(*AgentRequest_EnsureVolume)(nil),
		(*AgentRequest_WatchEvents)(nil),
	}
	file_proto_agent_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*AgentResponse_InspectByName)(nil),
		(*AgentResponse_Create)(nil),
		(*AgentResponse_ListImages)(nil),
		(*AgentResponse_ListByPrefix)(nil),
		(*AgentResponse_Empty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
