// TASKS.md 3.2: the wire contract for ADR 003's reverse-dialed gRPC
// agent. Message shapes mirror internal/docker's Go types (ContainerSpec,
// ContainerState, Event, ImageInfo, VolumeMount, PortBinding, Resources)
// field for field, deliberately: this is the exact narrow surface
// internal/agent.Transport already committed to in TASKS.md 3.1
// (docker.Runtime's own 9 methods, no more), not a redesign.
//
// AgentService is defined from the control plane's perspective (it is
// the gRPC *server*, since it has the one stable, well-known address
// every agent dials into) even though the agent is always the one who
// physically opens the connection (ADR 003: "the agent runs on every
// managed node and dials out"). Session is the one call an agent makes:
// a single long-lived bidirectional stream, kept open for the agent
// process's lifetime. The control plane sends AgentRequest messages down
// that stream (each carrying a request_id); the agent replies with
// AgentResponse messages carrying the same request_id, allowing many
// logical request/response pairs, including one persistently-streaming
// one (WatchEvents), to share the single physical connection. This is
// what "reverse-dialed" looks like at the RPC layer: TCP/TLS connection
// direction and logical request direction are independent.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: proto/agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Enroll_FullMethodName  = "/levelrail.agent.v1.AgentService/Enroll"
	AgentService_Session_FullMethodName = "/levelrail.agent.v1.AgentService/Session"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Enroll exchanges a one-time join token (internal/store.NodeJoinToken,
	// TASKS.md 3.1) for a signed client certificate, over a connection
	// that does not yet present a client cert (the token itself is the
	// credential for this one call). Called once per node, before Session
	// is ever called.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Session is the agent's one persistent connection, opened only after
	// Enroll (using the certificate Enroll returned for mTLS). The agent
	// never initiates a logical request on this stream, only responds to
	// AgentRequest messages arriving from the control plane, plus sending
	// ProxiedEvent messages unprompted (the streaming Docker-event
	// relay ADR 003 calls out: "the agent streams Docker events up to
	// the control plane rather than the control plane polling down").
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, AgentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SessionClient = grpc.BidiStreamingClient[AgentMessage, ControlMessage]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Enroll exchanges a one-time join token (internal/store.NodeJoinToken,
	// TASKS.md 3.1) for a signed client certificate, over a connection
	// that does not yet present a client cert (the token itself is the
	// credential for this one call). Called once per node, before Session
	// is ever called.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// Session is the agent's one persistent connection, opened only after
	// Enroll (using the certificate Enroll returned for mTLS). The agent
	// never initiates a logical request on this stream, only responds to
	// AgentRequest messages arriving from the control plane, plus sending
	// ProxiedEvent messages unprompted (the streaming Docker-event
	// relay ADR 003 calls out: "the agent streams Docker events up to
	// the control plane rather than the control plane polling down").
	Session(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentServiceServer) Session(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Session(&grpc.GenericServerStream[AgentMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SessionServer = grpc.BidiStreamingServer[AgentMessage, ControlMessage]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "levelrail.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentService_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
