import type { Component } from 'vue'
import {
  PhChartLineUp,
  PhChatsCircle,
  PhClockCounterClockwise,
  PhCloudArrowUp,
  PhDiscordLogo,
  PhDownloadSimple,
  PhFileCode,
  PhGithubLogo,
  PhGraph,
  PhListChecks,
  PhLockKey,
  PhMapTrifold,
  PhPlayCircle,
  PhPlugsConnected,
  PhRocketLaunch,
  PhScales,
  PhShieldCheck,
  PhSwap,
  PhTerminalWindow,
  PhTreeStructure,
  PhWrench,
} from '@phosphor-icons/vue'
import type { NavIconKey } from './navItems'

export const navIcons: Record<NavIconKey, Component> = {
  demo: PhPlayCircle,
  caseStudies: PhChartLineUp,
  architecture: PhTreeStructure,
  security: PhShieldCheck,
  roadmap: PhMapTrifold,
  featureStatus: PhListChecks,
  gettingStarted: PhRocketLaunch,
  installing: PhDownloadSimple,
  deploying: PhCloudArrowUp,
  multiNode: PhGraph,
  cli: PhTerminalWindow,
  api: PhPlugsConnected,
  appSpec: PhFileCode,
  troubleshooting: PhWrench,
  comparison: PhScales,
  alternative: PhSwap,
  changelog: PhClockCounterClockwise,
  privacy: PhLockKey,
  github: PhGithubLogo,
  discussions: PhChatsCircle,
  discord: PhDiscordLogo,
}
