import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import './index.css'

// routeTree.gen.ts is generated by @tanstack/router-plugin (see
// vite.config.ts) from the files under src/routes. It does not exist
// until `npm run dev` or `npm run build` has run at least once; it is
// gitignored, not hand-written.
import { routeTree } from './routeTree.gen'

const queryClient = new QueryClient()

// Router context carries the QueryClient (see routes/__root.tsx) so every
// route loader can prime the Query cache without a module-level import
// cycle back into this file.
const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('root element not found')
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
