import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import {
  MutationCache,
  QueryCache,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import './index.css'
import { isUnauthorized } from './lib/apiError'
import { clearStoredUsername } from './lib/authStore'

// routeTree.gen.ts is generated by @tanstack/router-plugin (see
// vite.config.ts) from the files under src/routes. It does not exist
// until `npm run dev` or `npm run build` has run at least once; it is
// gitignored, not hand-written.
import { routeTree } from './routeTree.gen'

// Filled in right after createRouter below with a plain closure, not a
// stored reference to the router itself: TanStack Router's type-level
// Register['router'] augmentation (the `declare module` block below)
// needs `typeof router` on the `const router = createRouter(...)`
// assignment to stay exactly as inferred, un-widened by ever flowing
// through a separately-typed variable first (that produced a real tsc
// error, a self-referential mismatch between the router's type before
// and after the Register augmentation resolves). A plain function
// reference sidesteps the whole issue.
let navigateToLogin: (() => void) | null = null

// Global 401 handling (docs-local/research/dashboard-gap-audit-and-
// devmode.md gap #2): every fetcher under src/queries/*.ts now throws an
// ApiError with a real status code (lib/apiError.ts) instead of a plain
// Error, so a 401 arriving from any query or mutation, anywhere in the
// app, is detected here in exactly one place and redirected to /login,
// distinct from how a 404/500 still renders in each route's own error
// boundary (AppDetailError and friends keep working exactly as before,
// since onError here only acts on 401).
function handleQueryError(error: unknown): void {
  if (isUnauthorized(error)) {
    clearStoredUsername()
    navigateToLogin?.()
  }
}

const queryClient = new QueryClient({
  queryCache: new QueryCache({ onError: handleQueryError }),
  mutationCache: new MutationCache({ onError: handleQueryError }),
})

// Router context carries the QueryClient (see routes/__root.tsx) so every
// route loader can prime the Query cache without a module-level import
// cycle back into this file.
const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
})
navigateToLogin = () => {
  // A failed login/register submission is itself a 401/... mutation that
  // flows through this same shared mutationCache, so this can fire while
  // already sitting on /login (LoginForm renders its own error message
  // from that same rejection). Guarded here rather than skipped entirely,
  // since a real mid-session 401 on any other route still needs this.
  if (router.state.location.pathname === '/login') {
    return
  }
  void router.navigate({ to: '/login' })
}

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('root element not found')
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
