import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import type { NodeResource } from '../types/nodeDetail'
import { AgentOutdatedBadge, NodeCertBadge } from './NodeCertBadge'
import { ReenrollNodeDialog } from './ReenrollNodeDialog'
import { RevokeNodeCertDialog } from './RevokeNodeCertDialog'

function formatDate(iso?: string): string {
  return iso ? new Date(iso).toLocaleString() : 'Never'
}

function Item({
  label,
  children,
  mono = false,
}: {
  label: string
  children: React.ReactNode
  mono?: boolean
}) {
  return (
    <div className="min-w-0">
      <dt className="text-xs text-muted-foreground uppercase">{label}</dt>
      <dd
        className={`mt-1 truncate text-sm text-foreground ${mono ? 'font-mono text-xs' : ''}`}
      >
        {children}
      </dd>
    </div>
  )
}

// Agent identity on the node detail page: certificate lifecycle (ADR 021)
// and what the agent reported about its own build.
export function NodeAgentCard({ node }: { node: NodeResource }) {
  const { cert, agent } = node
  return (
    <Card>
      <CardHeader className="flex flex-row flex-wrap items-center justify-between gap-2">
        <CardTitle className="flex flex-wrap items-center gap-2">
          Agent
          <NodeCertBadge cert={cert} />
          <AgentOutdatedBadge agent={agent} />
        </CardTitle>
        <div className="flex items-center gap-2">
          <ReenrollNodeDialog node={node} />
          <RevokeNodeCertDialog node={node} />
        </div>
      </CardHeader>
      <CardContent>
        <dl className="grid grid-cols-2 gap-4 sm:grid-cols-3">
          <Item label="Certificate expires">{formatDate(cert?.not_after)}</Item>
          <Item label="Last renewed">
            {cert?.renewed_at
              ? `${formatDate(cert.renewed_at)} (generation ${cert.generation})`
              : 'Not since enrollment'}
          </Item>
          <Item label="Private key">
            {cert?.key_origin === 'server'
              ? 'Generated by the control plane (switches at next renewal)'
              : 'Generated on the node'}
          </Item>
          <Item label="Fingerprint" mono>
            {node.cert_fingerprint ?? 'Unknown'}
          </Item>
          <Item label="Version">
            {agent?.version || 'Not reported'}
            {agent?.min_version ? ` (minimum ${agent.min_version})` : ''}
          </Item>
          <Item label="Platform">
            {agent?.os ? `${agent.os}/${agent.arch ?? ''}` : 'Not reported'}
          </Item>
          {agent?.commit ? (
            <Item label="Commit" mono>
              {agent.commit}
            </Item>
          ) : null}
          {cert?.revoked_at ? (
            <Item label="Revoked">{formatDate(cert.revoked_at)}</Item>
          ) : null}
        </dl>
      </CardContent>
    </Card>
  )
}
